### ISSUE TITLE
Unable to add a channel (Wired)

### ISSUE THREAD

**Issue by sjfbo** [mauricekleine/rss-power#11]
Hello there 👋🏻 

It seems that I'm not able to add a new RSS channel in some specific cases.

A feed similar to `https://techcrunch.com/europe/feed/` would pass, but not `https://www.wired.com/feed/rss`.
When attempting to add the later, this is what I get in the devtools:

<img width="653" alt="Screenshot 2022-05-03 at 8 29 11" src="https://user-images.githubusercontent.com/6693498/166412590-f430db58-748f-4696-962f-e232b9e32e51.png">

The HTTP response I then receive is the following one:

```json
{
  "errors": {
    "origin": "Origin is invalid"
  }
}
```

I can provide more infos if needed. 🙇🏻 

Cheers.

**Comment by mauricekleine** [comment]
Thanks for reporting it @sjfbo! From the console I can see that there's an issue with the image - Wired doesn't send an image in their XML, so Prisma is complaining: `PrismaClientKnownRequestError: Null constraint violation on the fields: (`imageId`)`. I'll fix it tonight! 🙌

**Comment by mauricekleine** [comment]
@sjfbo @morajabi this should be fixed now :)

**Comment by sjfbo** [comment]
Good catch, thanks!
