### ISSUE TITLE
Entries sorting is incorrect

### ISSUE THREAD

**Issue by morajabi** [mauricekleine/rss-power#21]
What it should be:
![CleanShot 2022-05-04 at 00 16 00](https://user-images.githubusercontent.com/12202757/166554198-522ac8c5-5ee8-4f20-864b-41a7e86efbcd.png)

What it shows on RSS Power:
![CleanShot 2022-05-04 at 00 16 02](https://user-images.githubusercontent.com/12202757/166554194-26e43f9f-4103-4512-b859-16e6c9a75ce0.png)

Feed:
http://www.aaronsw.com/2002/feeds/pgessays.rss

**Comment by mauricekleine** [comment]
@morajabi aaah interesting, these articles don't have a `pubDate`. I guess in that case, I should stick to the original order that the items were provided in. And showing the "less than a minute ago" part doesn't make sense either.

Nice catch!

**Comment by mauricekleine** [comment]
@morajabi this should be fixed now, but only for new channels. Would you like me to delete the channel you added so you can re-add it, which should fix the order?
