### ISSUE TITLE
On mobile, cards' title is trimmed by time element

### ISSUE THREAD

**Issue by omar2205** [mauricekleine/rss-power#42]
Especially the less than a day:

![image](https://user-images.githubusercontent.com/1373867/166887694-f0f9895f-41a2-40fb-9fa8-10600888a5ee.png)

One fix may be, to move down? could be also in the footer, IDK.

![image](https://user-images.githubusercontent.com/1373867/166888367-5dc70e5e-40b4-44c1-90fd-647698d2c61b.png)

One side note, I feel the title could wrap to a new line instead of being clipped

**Comment by mauricekleine** [comment]
@omar2205 I went with a more compact approach that resembles how Twitter does these relative times :) 

https://user-images.githubusercontent.com/10089969/166973314-e1082b5b-150b-489d-a541-76c7e5cc5db8.png
