### ISSUE TITLE
The Channel logo is stretched

### ISSUE THREAD

**Issue by omar2205** [mauricekleine/rss-power#9]
![image](https://user-images.githubusercontent.com/1373867/166329356-5ec4acbe-5017-40ac-800e-0cfddc5cf4d4.png)

Setting `object-fit: cover;`

![image](https://user-images.githubusercontent.com/1373867/166329428-cc12cc76-f61e-4f17-bd72-9fa76747f732.png)

**Comment by omar2205** [comment]
The RSS http://feeds.bbci.co.uk/news/england/london/rss.xml

**Comment by mauricekleine** [comment]
@omar2205 thanks for reporting this, and providing testing data and a fix!
